[[redirects]]
from = "/beta"
to = "/blog/2025-06-25-introducing-agent-tars-beta.html"

[[redirects]]
from = "/quick-start"
to = "/guide/get-started/quick-start.html"


[[redirects]]
from = "/doc/*"
to = "https://preview.agent-tars.com/doc/*"

[[redirects]]
from = "/2025/04/11/difference-between-ui-tars-desktop-and-agent-tars-app"
to = "https://preview.agent-tars.com/2025/04/11/difference-between-ui-tars-desktop-and-agent-tars-app"

[[redirects]]
from = "/2025/03/25/mcp-brings-a-new-paradigm-to-layered-ai-app-development"
to = "https://preview.agent-tars.com/2025/03/25/mcp-brings-a-new-paradigm-to-layered-ai-app-development"

[[redirects]]
from = "/2025/03/18/announcing-agent-tars-app"
to = "https://preview.agent-tars.com/2025/03/18/announcing-agent-tars-app"